# Counting observations (1) by dataset

prefix qb: <http://purl.org/linked-data/cube#>
select ?dsd (count(distinct(?obs)) as ?count) where {
  ?obs qb:dataSet ?ds .
  ?ds qb:structure ?dsd .
  ?obs a qb:Observation .
} group by ?dsd

# Counting observations (2) by slice

prefix qb: <http://purl.org/linked-data/cube#>
select ?dsd (count(distinct?obs) as ?obs_count) where {
  ?ds a qb:DataSet .
  ?ds qb:structure ?dsd .
  ?ds qb:slice ?slice .
  ?slice qb:observation ?obs .
} group by ?dsd

# Querying DSDs

PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT ?dsd ?componentValue ?p ?o
WHERE {
?dsd a qb:DataStructureDefinition ;
     qb:component ?component .
?component ?componentType ?componentValue .
?componentValue ?p ?o .
FILTER (?componentType IN (qb:dimension, qb:measure, qb:attribute)) 
} ORDER BY ?dsd

# Alternative

PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT ?dsd ?component ?p ?o
WHERE {
?dsd a qb:DataStructureDefinition ;
  qb:component ?component .
?component ?p ?o .
} ORDER BY ?dsd

# Old

PREFIX sdmx: <http://purl.org/linked-data/sdmx#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX qb: <http://purl.org/linked-data/cube#>
SELECT DISTINCT ?dimensionu ?dimension ?code ?codelabel
WHERE {
{ GRAPH <http://lod.cedar-project.nl/resource/harmonization> {
    ?dimensionu a qb:DimensionProperty ;
    rdfs:label ?dimension .
    OPTIONAL {?dimensionu qb:codeList ?codelist .
    ?codelist skos:hasTopConcept ?code .
    ?code skos:prefLabel ?codelabel }
}}
UNION
{ SERVICE <http://worldbank.270a.info/sparql> {
    ?dimensionu a qb:DimensionProperty ;
    rdfs:label ?dimension .
    OPTIONAL {?dimensionu qb:codeList ?codelist .
    ?codelist skos:hasTopConcept ?code .
    ?code skos:prefLabel ?codelabel }
}}
} GROUP BY ?dimensionu ?dimension ORDER BY ?dimension